auth:
  cookie:
    secure: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    com.app.backend: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:backend},corr=%X{correlationId}] --- [%t] %logger{36} : %msg%n"
