spring:
  jpa:
    show-sql: true

auth:
  cookie:
    secure: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  file:
    name: /app/logs/spring-boot.log
  level:
    root: INFO
    com.app.backend: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
